// ============================================================
// storage.service.ts
// ============================================================
export { storageService } from "@/lib/services/storage.service";

// ============================================================
// notification.service.ts
// ============================================================
import { resend, EMAIL_FROM } from "@/lib/config/resend";
import { clientModel } from "@/lib/models/client.model";

export const notificationService = {
  async sendVerificationEmail(email: string, otp: string) {
    try {
      const result = await resend.emails.send({
        from: EMAIL_FROM,
        to: email,
        subject: "VScanMail — Verify your email",
        html: `<h2>Welcome to VScanMail</h2><p>Your verification code is: <strong>${otp}</strong></p><p>This code expires in 15 minutes.</p>`,
      });

      if ((result as any)?.error) {
        const err = (result as any).error;
        throw new Error(err?.message || "Resend returned an error");
      }

      if (process.env.NODE_ENV !== "production") {
        // eslint-disable-next-line no-console
        console.info(
          "[resend] verification email queued",
          JSON.stringify({
            to: email,
            from: EMAIL_FROM,
            id: (result as any)?.data?.id,
          })
        );
      }
    } catch (err: any) {
      const msg =
        err?.message ||
        err?.name ||
        "Resend email send failed. Check RESEND_API_KEY and EMAIL_FROM.";
      throw new Error(
        `Failed to send verification email. ${msg} (Tip: Resend requires a verified 'from' address/domain; for testing you can use onboarding@resend.dev.)`
      );
    }
  },

  async sendNewMailAlert(clientId: string, mailItem: any) {
    const client = await clientModel.findById(clientId);
    await resend.emails.send({
      from: EMAIL_FROM,
      to: client.email,
      subject: `VScanMail — New ${mailItem.type} received (${mailItem.irn})`,
      html: `<h2>New Mail Received</h2><p>IRN: ${mailItem.irn}</p><p>Type: ${mailItem.type}</p>${mailItem.ai_summary ? `<p><strong>AI Summary:</strong> ${mailItem.ai_summary}</p><p><em>Note: This summary was generated by AI (Sumxio) and should be verified.</em></p>` : ""}<p><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/mail/${mailItem.id}">View in dashboard</a></p>`,
    });
  },

  async sendTamperAlert(clientId: string, mailItem: any) {
    const client = await clientModel.findById(clientId);
    await resend.emails.send({
      from: EMAIL_FROM,
      to: client.email,
      subject: `VScanMail — TAMPER ALERT — ${mailItem.irn}`,
      html: `<h2 style="color:red;">Tampering Detected</h2><p>Mail item <strong>${mailItem.irn}</strong> shows signs of tampering.</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/mail/${mailItem.id}">Review immediately</a></p>`,
    });
  },

  async sendChequeAlert(clientId: string, cheque: any, validation: any) {
    const client = await clientModel.findById(clientId);
    const statusLabel =
      validation.status === "validated" ? "Ready for Review" : "Flagged — Needs Attention";
    await resend.emails.send({
      from: EMAIL_FROM,
      to: client.email,
      subject: `VScanMail — Cheque ${statusLabel} ($${cheque.amount_figures})`,
      html: `<h2>Cheque Processing Complete</h2><p>Amount: $${cheque.amount_figures}</p><p>Payee: ${cheque.beneficiary}</p><p>Status: ${statusLabel}</p><p>AI Confidence: ${Math.round(validation.confidence * 100)}%</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/cheques/${cheque.id}">Review and decide</a></p>`,
    });
  },
};

// ============================================================
// audit.service.ts
// ============================================================
import { auditLogModel } from "@/lib/models/shared.models";

export const auditService = {
  async log(params: {
    actor: string;
    action: string;
    entity: string;
    details?: any;
    ip?: string;
  }) {
    await auditLogModel.append({
      actor_id: params.actor,
      action: params.action,
      entity_type: params.action.split(".")[0], // e.g., "cheque" from "cheque.approved"
      entity_id: params.entity,
      details: params.details || {},
      ip_address: params.ip || null,
    });
  },
};

// ============================================================
// billing.service.ts
// ============================================================
import { usageEventModel } from "@/lib/models/shared.models";
// `clientModel` is already imported above for notificationService.

const UNIT_COSTS: Record<string, number> = {
  envelope_scan: 0.5,
  ai_summary: 2.0,
  cheque_validation: 3.0,
  cheque_approved: 0,
  storage_gb: 0.1,
};

export const billingService = {
  async trackUsage(clientId: string, eventType: string, quantity: number) {
    const unitCost = UNIT_COSTS[eventType] || 0;
    const totalCost = unitCost * quantity;

    await usageEventModel.create({
      client_id: clientId,
      event_type: eventType,
      quantity,
      unit_cost: unitCost,
      total_cost: totalCost,
    });

    // For top-up clients, deduct from wallet
    const client = await clientModel.findById(clientId);
    if (client.plan_type === "topup" && totalCost > 0) {
      await clientModel.updateWalletBalance(clientId, -totalCost);

      // Check if wallet is low
      const updated = await clientModel.findById(clientId);
      if (updated.wallet_balance < 5) {
        // Could trigger a low-balance notification here
      }
    }
  },

  async getUsageSummary(clientId: string, from?: string, to?: string) {
    const events = await usageEventModel.sumByClient(clientId, from, to);

    const summary: Record<string, { quantity: number; cost: number }> = {};
    for (const e of events) {
      if (!summary[e.event_type]) {
        summary[e.event_type] = { quantity: 0, cost: 0 };
      }
      summary[e.event_type].quantity += e.quantity;
      summary[e.event_type].cost += e.total_cost;
    }

    const totalCost = Object.values(summary).reduce(
      (sum, s) => sum + s.cost,
      0
    );

    return { breakdown: summary, totalCost: Math.round(totalCost * 100) / 100 };
  },
};
