import { resend, EMAIL_FROM } from "./resend.config";
import { clientModel } from "../clients/client.model";

export const notificationService = {
  async sendVerificationEmail(email: string, otp: string) {
    try {
      const result = await resend.emails.send({
        from: EMAIL_FROM,
        to: email,
        subject: "VScanMail — Verify your email",
        html: `<h2>Welcome to VScanMail</h2><p>Your verification code is: <strong>${otp}</strong></p><p>This code expires in 15 minutes.</p>`,
      });

      if ((result as any)?.error) {
        const err = (result as any).error;
        throw new Error(err?.message || "Resend returned an error");
      }

      if (process.env.NODE_ENV !== "production") {
        // eslint-disable-next-line no-console
        console.info(
          "[resend] verification email queued",
          JSON.stringify({
            to: email,
            from: EMAIL_FROM,
            id: (result as any)?.data?.id,
          })
        );
      }
    } catch (err: any) {
      const msg =
        err?.message ||
        err?.name ||
        "Resend email send failed. Check RESEND_API_KEY and EMAIL_FROM.";
      throw new Error(
        `Failed to send verification email. ${msg} (Tip: Resend requires a verified 'from' address/domain; for testing you can use onboarding@resend.dev.)`
      );
    }
  },

  async sendNewMailAlert(clientId: string, mailItem: any) {
    const client = await clientModel.findById(clientId);
    await resend.emails.send({
      from: EMAIL_FROM,
      to: client.email,
      subject: `VScanMail — New ${mailItem.type} received (${mailItem.irn})`,
      html: `<h2>New Mail Received</h2><p>IRN: ${mailItem.irn}</p><p>Type: ${mailItem.type}</p>${mailItem.ai_summary ? `<p><strong>AI Summary:</strong> ${mailItem.ai_summary}</p><p><em>Note: This summary was generated by AI (Sumxio) and should be verified.</em></p>` : ""}<p><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/mail/${mailItem.id}">View in dashboard</a></p>`,
    });
  },

  async sendTamperAlert(clientId: string, mailItem: any) {
    const client = await clientModel.findById(clientId);
    await resend.emails.send({
      from: EMAIL_FROM,
      to: client.email,
      subject: `VScanMail — TAMPER ALERT — ${mailItem.irn}`,
      html: `<h2 style="color:red;">Tampering Detected</h2><p>Mail item <strong>${mailItem.irn}</strong> shows signs of tampering.</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/mail/${mailItem.id}">Review immediately</a></p>`,
    });
  },

  async sendChequeAlert(clientId: string, cheque: any, validation: any) {
    const client = await clientModel.findById(clientId);
    const statusLabel =
      validation.status === "validated" ? "Ready for Review" : "Flagged — Needs Attention";
    await resend.emails.send({
      from: EMAIL_FROM,
      to: client.email,
      subject: `VScanMail — Cheque ${statusLabel} ($${cheque.amount_figures})`,
      html: `<h2>Cheque Processing Complete</h2><p>Amount: $${cheque.amount_figures}</p><p>Payee: ${cheque.beneficiary}</p><p>Status: ${statusLabel}</p><p>AI Confidence: ${Math.round(validation.confidence * 100)}%</p><p><a href="${process.env.NEXT_PUBLIC_APP_URL}/dashboard/cheques/${cheque.id}">Review and decide</a></p>`,
    });
  },
};
